version: '3.8'

services:
  firebase-app:
    build:
      context: .
    ports:
    - "3000:3000"
    - "9229:9229"
    working_dir: "/src"
    volumes:
    - "./src:/src"
    - node_modules_volume:/src/node_modules
    tty: true
    environment:
    - CHOKIDAR_USEPOLLING=true

volumes:
  node_modules_volume:
